version: "3"
services:
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    container_name: ex7_api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ex7_local
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: ex7_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: ex7_local
    ports:
      - "5432:5432"
    expose:
      - "5432"